alter table public.pois
  add column if not exists partner_profile jsonb not null default '{}'::jsonb;

create table if not exists public.poi_partner_events (
  id bigint generated by default as identity primary key,
  poi_id bigint not null references public.pois(id) on delete cascade,
  event_type text not null check (event_type in ('profile_view', 'whatsapp_click')),
  visitor_key text,
  created_at timestamptz not null default now()
);

create index if not exists poi_partner_events_poi_created_idx
  on public.poi_partner_events (poi_id, created_at desc);
create index if not exists poi_partner_events_type_created_idx
  on public.poi_partner_events (event_type, created_at desc);

alter table public.poi_partner_events enable row level security;
revoke all on public.poi_partner_events from anon, authenticated;
grant select, insert on public.poi_partner_events to service_role;
grant usage, select on sequence public.poi_partner_events_id_seq to service_role;

create or replace function public.track_poi_partner_event(
  target_poi_id bigint,
  target_event_type text,
  target_visitor_key text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_event_type not in ('profile_view', 'whatsapp_click') then
    raise exception 'Invalid event type';
  end if;

  if not exists (select 1 from public.pois where id = target_poi_id) then
    raise exception 'POI not found';
  end if;

  insert into public.poi_partner_events (poi_id, event_type, visitor_key)
  values (target_poi_id, target_event_type, left(nullif(trim(target_visitor_key), ''), 120));
end;
$$;

revoke all on function public.track_poi_partner_event(bigint, text, text) from public;
grant execute on function public.track_poi_partner_event(bigint, text, text) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'business-assets',
  'business-assets',
  true,
  6291456,
  array['image/jpeg','image/png','image/webp','application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.validate_partner_discount_code(target_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  manager_email text;
  code_row public.discount_codes;
  poi_row public.pois;
  offer jsonb := '{}'::jsonb;
  rules jsonb := '{}'::jsonb;
  italy_now timestamp := timezone('Europe/Rome', now());
  start_time time;
  end_time time;
  max_daily integer := 0;
  used_today integer := 0;
begin
  manager_email := lower(auth.jwt() ->> 'email');
  if manager_email is null or manager_email = '' then
    raise exception 'Missing authenticated user email';
  end if;

  select * into code_row
  from public.discount_codes
  where upper(code) = upper(trim(target_code))
  limit 1;
  if code_row.id is null then raise exception 'Code not found'; end if;

  select * into poi_row from public.pois where id = code_row.poi_id limit 1;
  if poi_row.id is null then raise exception 'POI not found'; end if;
  if not (manager_email = any(string_to_array(lower(replace(coalesce(poi_row.emails, ''), ' ', '')), ','))) then
    raise exception 'Not authorized for this POI';
  end if;
  if coalesce(poi_row.discount, 0) <= 0 then raise exception 'Offer is no longer active'; end if;
  if code_row.status = 'used' then raise exception 'Code already used'; end if;
  if code_row.expires_at <= now() then
    update public.discount_codes set status = 'expired' where id = code_row.id;
    raise exception 'Code expired';
  end if;

  begin
    offer := coalesce(nullif(code_row.discount_info, '')::jsonb, '{}'::jsonb);
  exception when others then
    offer := '{}'::jsonb;
  end;
  rules := coalesce(offer -> 'rules', '{}'::jsonb);

  if coalesce(rules ->> 'daily_start', '') ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then
    start_time := (rules ->> 'daily_start')::time;
  end if;
  if coalesce(rules ->> 'daily_end', '') ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then
    end_time := (rules ->> 'daily_end')::time;
  end if;
  if start_time is not null and end_time is not null then
    if start_time <= end_time and not (italy_now::time >= start_time and italy_now::time <= end_time) then
      raise exception 'Code outside the allowed time window';
    elsif start_time > end_time and not (italy_now::time >= start_time or italy_now::time <= end_time) then
      raise exception 'Code outside the allowed time window';
    end if;
  end if;

  max_daily := greatest(0, least(10000, coalesce(nullif(rules ->> 'max_daily_redemptions', '')::integer, 0)));
  if max_daily > 0 then
    select count(*) into used_today
    from public.discount_codes
    where poi_id = code_row.poi_id
      and status = 'used'
      and valid_day = code_row.valid_day;
    if used_today >= max_daily then raise exception 'Daily redemption limit reached'; end if;
  end if;

  update public.discount_codes
  set status = 'used', validated_at = now(), validated_by = auth.uid()
  where id = code_row.id
  returning * into code_row;

  return jsonb_build_object(
    'ok', true,
    'message', 'Discount validated',
    'code', code_row.code,
    'discount', code_row.discount,
    'discount_info', code_row.discount_info,
    'poi_id', poi_row.id,
    'poi_name', poi_row.name,
    'user_email', code_row.user_email,
    'created_at', code_row.created_at,
    'validated_at', code_row.validated_at
  );
end;
$$;

